### ISSUE TITLE
Cross origin requests are only supported for HTTP.

### ISSUE THREAD

**Issue by AZLDC** [onevcat/UniWebView-Docs#16]
I'm Novice with html, Mac, ios...
working for html project, and... we need to build ms-windows standalong version, Mac standalong version,Android app, IOS App...

don't care about windows and Mac, they are work fine with other way.
the qustion is :
Android app I choice to use UniWebView, and it work fine.
and **_IOS_** I choice it too.
but it's show me "**Cross origin requests are only supported for HTTP.**"

I can read local html file, but it can't load the other local file in that page.

I'm a ms-windows 7 user, build IOS with Unity 2017.1, UniWebView 2
what should I do with my project make it work fine?

Mac and IOS make me feel frustrated...

**Comment by AZLDC** [comment]
some one help me please...

**Comment by AZLDC** [comment]
now using UniWebView 3 still have this issue...

**Comment by andrisole92** [comment]
Same issue.

**Comment by andrisole92** [comment]
@onevcat can you add something from here:
https://stackoverflow.com/a/47000950/7322008

**Comment by javimillan6** [comment]
Some news about this or some way to solve it? I have the same problem.

**Comment by onevcat** [comment]
This should be already added in version 3.8.0. It's now under review of Unity Asset Store and you should be able to upgrade and set it after you upgrade.

See http://docs.uniwebview.com/api/#setallowfileaccessfromfileurls

**Comment by javimillan6** [comment]
Hello, 

I just tried this method and now i dont have problems with cross-origin, but I still have the same problem when trying to open a local file inside an iframe in iOS. 
XCode console:
Received an unexpected URL from the web process: 'file:///var/mobile/Containers/Data/Application/.....'

Received an invalid message
"WebPageProxy.DecidePolicyForNavigationAction" from the web process.
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

What Can i do to solve this? Please i need it.

Thanks.
