### ISSUE TITLE
Can't open url with fragment identifier on iOS

### ISSUE THREAD

**Issue by Suvitruf** [onevcat/UniWebView-Docs#25]
Can't open urls with fragment identifier like `http://example.com/#/plugin/54354543`.

Right now using this hack:

    string hashPart = "plugin/" + m_GameId;
    m_WebView.Show(false, UniWebViewTransitionEdge.None, 0.4f, () => {
             m_WebView.EvaluateJavaScript("window.location.hash = '" + hashPart + "'");
    });

But could you make it able to open urls with fragment identifier?

**Comment by onevcat** [comment]
Try to load your URL with encoding skipped might solve this:

```csharp
webView.Load("http://example.com/#/plugin/54354543", true);
```
