### ISSUE TITLE
adjustInset doesn't work on Android

### ISSUE THREAD

**Issue by Suvitruf** [onevcat/UniWebView-Docs#29]
![Image of Yaktocat](https://monosnap.com/image/kilCWUIazoqvvKyHUpIZ2bgz3CIco5.png)

No input. It's below the keyboard.

**Comment by romantic123fly** [comment]
I have the same problem as you. Are you making good progress so far?

**Comment by Suvitruf** [comment]
Yes, but it's ugly. You can check the code and the way I've done it on SO: https://ru.stackoverflow.com/q/883687/15479

Basically, I've subscribed on global listener `addOnGlobalLayoutListener` and changed padding above the input field when needed.

**Comment by onevcat** [comment]
There is indeed a native solution to resize the web view when the keyboard comes up. However, it will bring another [issue in the Android system](https://issuetracker.google.com/issues/36911528), which will cause the layout breaks, so we cannot use it for web view here.

The best solution, for now, is solving it in the web page side. Either leave some blank in the bottom of your page to let user can scroll, or add some JavaScript on your page to listen to the keyboard event as above.
