### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pjc0247** [onevcat/UniWebView-Docs#39]
Hi, I'm considering to buy your `UniWebView` asset.

Does your plugin works with `UGUI.ScrollView`? 
I mean, If your `WebView` component is being located under `ScrollView`, it can be scrolled with scroll view component or not?

(UI masking is not important to me.)

Thanks.

**Comment by onevcat** [comment]
Hi,

UniWebView is a layer above the whole Unity game, so it is not working with Unity GUI out of the box. Since you can set the web view position and size as you need, so it is possible to make it sync with the scroll view, but that is not easy.
