### ISSUE TITLE
Does UniWeb support websites with self signed certificates for https?

### ISSUE THREAD

**Issue by oluwaseyeayinla** [onevcat/UniWebView-Docs#4]
I'm currently have an issue accessing websites with self signed certificates with an android unity3D plugin and would like to know if UniWeb provides support for those kind of websites.

**Comment by onevcat** [comment]
Maybe this could help you: http://docs.uniwebview.com/#/latest/api/uniwebview.html?id=addsslexceptiondomain

**Comment by oluwaseyeayinla** [comment]
Thanks
